apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    job: mysql-service
    app: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - name: dbport
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer
